### PR TITLE
cname-change

### PR DESCRIPTION
**Pull request by aashishkapur**

### CODE REVIEW

**Comment by sskhandek** [comment]
I don't think this actually does anything: http://stackoverflow.com/questions/16454088/can-github-pages-cname-file-contain-more-than-one-domain

**Review by pranaygp — CHANGES_REQUESTED** [review]
I'm pretty sure you can't do that.

CNAME files aren't allowed multiple lines

**Review by sskhandek — CHANGES_REQUESTED** [review]
Check the link in my comment

**Comment by aashishkapur** [comment]
Yeah, i just saw that.

We should probably be using the `.org` domain primarily, so it might make sense to set up a DNS redirect from the `.com` to the `.org` and use the .org here

**Comment by pranaygp** [comment]
In fact I believe this would break the existing CNAM record

**Comment by aashishkapur** [comment]
if @sskhandek @bluedrops can make that redirect(I don't have access to the DNS), this can be merged

**Comment by sskhandek** [comment]
I'll leave it to @bluedrops to do that, but it is critical this shouldn't be merged until that is done. We'll leave this waiting until Simon's done that

**Review by pranaygp — APPROVED** [review]

**Pull request closed without merging**
